import type { Idea } from '@/types';
import dayjs from 'dayjs';

const now = dayjs();

export const MOCK_IDEAS: Idea[] = [
  {
    id: '1',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 23,
    transcription:
      'Need to send the project proposal to the client before end of day today. Make sure to include the revised pricing section.',
    manualNote: '',
    extractedTime: now.hour(17).minute(0).second(0).toISOString(),
    timeCategory: 'today',
    tags: ['work', 'client'],
    isCompleted: false,
    completedAt: null,
    createdAt: now.subtract(2, 'hour').toISOString(),
    updatedAt: now.subtract(2, 'hour').toISOString(),
  },
  {
    id: '2',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 15,
    transcription: "Pick up dry cleaning on the way home tonight. Don't forget — they close at 7.",
    manualNote: '',
    extractedTime: now.hour(19).minute(0).second(0).toISOString(),
    timeCategory: 'today',
    tags: ['personal', 'errands'],
    isCompleted: true,
    completedAt: now.subtract(30, 'minute').toISOString(),
    createdAt: now.subtract(4, 'hour').toISOString(),
    updatedAt: now.subtract(30, 'minute').toISOString(),
  },
  {
    id: '3',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 42,
    transcription:
      "Call mom on Wednesday evening. She mentioned something about needing help with her laptop. Also remind her about Sunday's family dinner.",
    manualNote: 'Her number is saved as "Mom Home"',
    extractedTime: now.add(2, 'day').hour(19).minute(0).second(0).toISOString(),
    timeCategory: 'thisWeek',
    tags: ['personal', 'family'],
    isCompleted: false,
    completedAt: null,
    createdAt: now.subtract(1, 'day').toISOString(),
    updatedAt: now.subtract(1, 'day').toISOString(),
  },
  {
    id: '4',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 31,
    transcription:
      'Team retrospective meeting on Thursday at 2pm. Prepare three things that went well and two areas for improvement this sprint.',
    manualNote: '',
    extractedTime: now.add(3, 'day').hour(14).minute(0).second(0).toISOString(),
    timeCategory: 'thisWeek',
    tags: ['work', 'meeting'],
    isCompleted: false,
    completedAt: null,
    createdAt: now.subtract(6, 'hour').toISOString(),
    updatedAt: now.subtract(6, 'hour').toISOString(),
  },
  {
    id: '5',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 18,
    transcription: 'Buy a birthday gift for Sarah. Her birthday is this Friday. She mentioned liking pottery or cooking classes.',
    manualNote: 'Budget around $50-80',
    extractedTime: now.add(4, 'day').toISOString(),
    timeCategory: 'thisWeek',
    tags: ['personal', 'shopping'],
    isCompleted: false,
    completedAt: null,
    createdAt: now.subtract(3, 'hour').toISOString(),
    updatedAt: now.subtract(3, 'hour').toISOString(),
  },
  {
    id: '6',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 55,
    transcription:
      'Book a dental appointment — overdue by about 3 months now. Try to schedule it for sometime next month when work slows down.',
    manualNote: 'Dr. Kim: 555-0147',
    extractedTime: now.add(3, 'week').toISOString(),
    timeCategory: 'future',
    tags: ['health', 'personal'],
    isCompleted: false,
    completedAt: null,
    createdAt: now.subtract(2, 'day').toISOString(),
    updatedAt: now.subtract(2, 'day').toISOString(),
  },
  {
    id: '7',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 38,
    transcription:
      'Idea for side project: a simple habit tracker that sends a weekly summary email. Could be built with Next.js and Resend. Could charge $5/month.',
    manualNote: 'Research Resend API pricing first',
    extractedTime: now.add(2, 'month').toISOString(),
    timeCategory: 'future',
    tags: ['project', 'ideas'],
    isCompleted: false,
    completedAt: null,
    createdAt: now.subtract(3, 'day').toISOString(),
    updatedAt: now.subtract(3, 'day').toISOString(),
  },
  {
    id: '8',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 12,
    transcription: 'Look into getting a standing desk — been having back pain. Check Flexispot and Uplift brands.',
    manualNote: '',
    extractedTime: now.add(1, 'month').toISOString(),
    timeCategory: 'future',
    tags: ['health', 'shopping'],
    isCompleted: false,
    completedAt: null,
    createdAt: now.subtract(5, 'day').toISOString(),
    updatedAt: now.subtract(5, 'day').toISOString(),
  },
  {
    id: '9',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 27,
    transcription:
      "Interesting article idea: write about how voice-first interfaces are changing productivity tools. Focus on the shift from typing to speaking for quick capture.",
    manualNote: '',
    extractedTime: null,
    timeCategory: 'inbox',
    tags: ['writing', 'ideas'],
    isCompleted: false,
    completedAt: null,
    createdAt: now.subtract(1, 'hour').toISOString(),
    updatedAt: now.subtract(1, 'hour').toISOString(),
  },
  {
    id: '10',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 20,
    transcription:
      'The color palette for the new design should lean warmer — maybe amber or terracotta tones instead of the current cold blue. Feels more approachable.',
    manualNote: 'Test against WCAG contrast ratios',
    extractedTime: null,
    timeCategory: 'inbox',
    tags: ['design', 'work'],
    isCompleted: false,
    completedAt: null,
    createdAt: now.subtract(45, 'minute').toISOString(),
    updatedAt: now.subtract(45, 'minute').toISOString(),
  },
  {
    id: '11',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 9,
    transcription: 'Try making shakshuka this weekend. Need eggs, canned tomatoes, peppers, and cumin.',
    manualNote: '',
    extractedTime: null,
    timeCategory: 'inbox',
    tags: ['food', 'personal'],
    isCompleted: false,
    completedAt: null,
    createdAt: now.subtract(20, 'minute').toISOString(),
    updatedAt: now.subtract(20, 'minute').toISOString(),
  },
  {
    id: '12',
    audioUrl: null,
    audioBlobUrl: null,
    audioDuration: 33,
    transcription:
      'Read "Thinking Fast and Slow" by Kahneman — highly recommended by two colleagues this week. Get the audiobook version for commuting.',
    manualNote: '',
    extractedTime: null,
    timeCategory: 'inbox',
    tags: ['reading', 'learning'],
    isCompleted: false,
    completedAt: null,
    createdAt: now.subtract(8, 'hour').toISOString(),
    updatedAt: now.subtract(8, 'hour').toISOString(),
  },
];

// Sample transcriptions for mock AI processing after recording
export const MOCK_TRANSCRIPTIONS = [
  'Remember to follow up with the team about the deadline extension request.',
  'Great idea from the podcast: start each morning with a "highlight" — one thing that must happen today.',
  'Look up that restaurant Maria mentioned — it was called something like "The Blue Door" in the arts district.',
  'Need to renew car insurance before the end of this month. Check if bundling with home insurance saves money.',
  'Think about restructuring the weekly reports to be more visual — less text, more charts.',
  "Interesting concept: what if meetings had a strict 15-minute cap by default? Study the research on this.",
  'Order more coffee beans — getting low. Try the Ethiopian blend this time.',
  'The new feature idea: let users pin their top 3 ideas to the top of the list for quick access.',
];
